### ISSUE TITLE
Refactor around momentjs

### ISSUE THREAD

**Issue by ClickerMonkey** [ClickerMonkey/dayspan#14]
Try to remove reference to moment. If I recall correctly, the main advantage to moment was accurate days-between calculations specifically around DST. 

A pluggable interface should be created for locales (weekdays/months) - which is another dependency on moment.

**Comment by ClickerMonkey** [comment]
I have. Add my own locale object for the few things that are localizable and add a double reference for each Day object so you can set specific locale or global locales. Date formatting will use Intl.DateTimeFormat and moment will be replaced with JS Date

**Comment by naulacambra** [comment]
Great, nice to know. If do you any help is needed, let us know.

**Comment by naulacambra** [comment]
How is this doing? Any forecast about when it will be ready? No rushing, just checking :)

**Comment by ClickerMonkey** [comment]
@naulacambra Working on this now, I HOPE it's done within the week.
