### ISSUE TITLE
I created a `parseICalString()` function which might be useful to dayspan

### ISSUE THREAD

**Issue by thefliik** [ClickerMonkey/dayspan#16]
_I maintain another javascript recurring event library, [rSchedule](https://gitlab.com/john.carroll.p/rschedule). I ran across dayspan a while back and starred it out of professional curiosity. This is just an FYI in case you find it useful_

I recently had cause to [build an function to parse ical strings](https://gitlab.com/john.carroll.p/rschedule/tree/master/packages/ical-tools), including `VCALENDAR` and `VEVENT` components / subcomponents. I figure other libraries like dayspan might also find the function useful, so I've [published it as part of a separate package](https://gitlab.com/john.carroll.p/rschedule/tree/master/packages/ical-tools) (though [the code is pretty simple](https://gitlab.com/john.carroll.p/rschedule/blob/ae3d2f82b7bc77479f1f3c3b121ee6abcf912e48/packages/ical-tools/src/lib/parser.ts), so feel free to copy-paste it into dayspan instead).

Anyway, not sure if dayspan already has the ability to import complex VCALENDAR strings, but, if not, and if at some point in the future you decide you want to add this functionality, `@rschedule/ical-tools` might be useful for you.

Feel free to close this issue.

**Comment by thefliik** [comment]
Having found https://github.com/mozilla-comm/ical.js/, I think it's a better ical parsing library.

**Comment by ClickerMonkey** [comment]
Thank you for the heads up! dayspan does not support that, but I definitely want it to in the future!
