### ISSUE TITLE
jest-cli dependency

### ISSUE THREAD

**Issue by naulacambra** [ClickerMonkey/dayspan#17]
It's really necessary that `jest-cli` package be a `dependency` instead of `dev-dependency`?

``` json
...
"dependencies": {
    "jest-cli": "22.4.3",
    "moment": "2.22.1"
},
...
```

I didn't notice it until an [npm vulnerability](https://www.npmjs.com/advisories/786) appeared with `npm audit` command.

> Overview
Version of braces prior to 2.3.1 are vulnerable to Regular Expression Denial of Service (ReDoS). Untrusted input may cause catastrophic backtracking while matching regular expressions. This can cause the application to be unresponsive leading to Denial of Service.

The dependency path is 
`dayspan > jest-cli > micromatch > braces`

Jest have fixed the vulnerability on its [24 version](https://github.com/facebook/jest/issues/7917)

Should I make a PR removing the dependency?

**Comment by naulacambra** [comment]
Any update on this @ClickerMonkey?

**Comment by ustun** [comment]
I agree that it is accidental. In the meantime, we forked dayspan to move the jest deps to devDeps and have another forked version of dayspan-vuetify that depends on our fork.

**Comment by ustun** [comment]
Created a PR for this issue: https://github.com/ClickerMonkey/dayspan/pull/22
