### ISSUE TITLE
Efficient way to set recurrence "every" value and its end by amount of occurrences

### ISSUE THREAD

**Issue by bupaev** [ClickerMonkey/dayspan#18]
Hi Philip! Thanks again for this great library!

Сould you clarify whether there are straightforward API methods to
1) set `every` value
2) define the end of recurrence by amount of occurrences. 

_Screenshot from Google Calendar for example of this settings_
![screenshot 2019-03-01 at 18 03 09](https://user-images.githubusercontent.com/1748949/53637268-e6ddfe00-3c4c-11e9-9866-a1891b5f0079.png)

It seems pretty standard functionality but I haven't found simple direct ways to set it up 😔 

If there is no simple API for this stuff, could you recommend the most efficient way to make it with current API?

Thank you in advance!

**Comment by ClickerMonkey** [comment]
This library doesn't currently support a maximum number of occurrences, it's too computationally expensive. The library only has the ability to say `given this day, is there an event?` - and it can answer that with very simple checks. If it were any more complicated performance would greatly suffer. 

You could calculate the `end` date for your schedule by using https://clickermonkey.github.io/dayspan/docs/classes/schedule.html#nextdays . You pass the start date and the number of occurrences in the input - and you should have all events.
