### ISSUE TITLE
How to control the counts of events in schedule?

### ISSUE THREAD

**Issue by guoxiangke** [ClickerMonkey/dayspan#20]
Hi, I use https://jakubroztocil.github.io/rrule/ , there is a "count"  config how many the events should occurs. 
How to config in dayspan? I tested "durationInDays" config, but not work.
thanks.
![image](https://user-images.githubusercontent.com/1160703/54861766-0529ac00-4d6a-11e9-9a32-958b50db4666.png)

**Comment by bupaev** [comment]
@guoxiangke As I understood you can't control the counts of events (https://github.com/ClickerMonkey/dayspan/issues/18), you can set the end date only. So I think you should try to implement your own calculation of end date based on the number of events and event's frequency

**Comment by ClickerMonkey** [comment]
https://github.com/ClickerMonkey/dayspan/issues/18
