### ISSUE TITLE
Is there a simple way to convert an ISOdate or moment.js object to a dayspan object?

### ISSUE THREAD

**Issue by goldfingersvox** [ClickerMonkey/dayspan#25]
I really want to integrate the calendar library based on this tool into my project but I need for there to be a simple way for it to communicate with ISOdate or moment.js. The documentation is unclear if there's a simple conversion or if I can just feed one of those into the library. Thanks!

**Comment by ClickerMonkey** [comment]
There are multiple *to* methods on `Day` that can be used to  translate it to a format which other libraries support. `toArray` outputs an array momentjs can understand perfectly.

https://github.com/ClickerMonkey/dayspan/blob/7169b7f/src/Day.ts#L903
